# Generated by Django 5.1 on 2024-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitt',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
